name: trigger jenkins job
on: [push]
jobs:

  first_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://54.226.60.205:8080/"
        user: "admin"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "foobar"