name: Sample Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        -   name: Install Cowsay
            run: |
                sudo apt install cowsay -y

        -   name: Cowsay initiation
            run: cowsay -f dragon "Ooooooooooo" >> dragon.txt

        -   name: Test File
            run: grep -i "dragon" dragon.txt

        -   name: Cat dragon file
            run: cat dragon.txt