name: Sample Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        -   name: checkout repo
            uses: actions/checkout@v4

        -   name: Run shell script
            run: |
             chmod +x dragon.shell
             ./dragon.sh

        -   name: Upload dragon file
            uses: actions/upload-artifact@v4
            with:
                name: Uploading-Dragon
                path: dragon.txt

    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:

        -   name: Download File
            uses: actions/download-artifact@v4
            with:
                name: Uploading-Dragon

        -   name: Cat Dragon
            run: cat dragon.txt
